services:

  db:
    image: postgres:16 #PostgreSQL versión 16

    container_name: feedback_db

    environment: #credenciales
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feedbacksdk

    ports:
      - "5432:5432"

    volumes: #la db no se borra al apagar docker
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: